### ISSUE TITLE
how to get the music data?

### ISSUE THREAD

**Issue by oxygenman** [google-research/mint#10]
how to get the music data  which used in the preprocessing "--audio_dir="/mnt/data/AIST/music/" ?

**Comment by funnyQZQ** [comment]
you can get music data from the [AIST++](https://aistdancedb.ongaaccel.jp/database_download/) official website.

**Comment by oxygenman** [comment]
> you can get music data from the [AIST++](https://aistdancedb.ongaaccel.jp/database_download/) official website.

oaky, thank you very much. by the way, do you  know how to visualize the evaluator's .npy results?

**Comment by funnyQZQ** [comment]
The output .npy file contains translation coordinates and rotation info in 3x3 matrix format, you can convert the rotation infomation into angle-axis format, which can be used as the pose parameters in SMPL model.

**Comment by oxygenman** [comment]
> The output .npy file contains translation coordinates and rotation info in 3x3 matrix format, you can convert the rotation infomation into angle-axis format, which can be used as the pose parameters in SMPL model.

yes, I know the mean of the results ,but, is there a ready script to do this? i am new to this,so i will very appreciate if you can share more details  to me.

**Comment by funnyQZQ** [comment]
You can refer to the [script](https://github.com/google/aistplusplus_api#visualize-the-smpl-mesh) to visualize SMPL mesh according  to the output from mint.

**Comment by funnyQZQ** [comment]
E-mail me for more details, funnyqzq@gmail.com

**Comment by hzy-del** [comment]
> You can refer to the [script](https://github.com/google/aistplusplus_api#visualize-the-smpl-mesh) to visualize SMPL mesh according to the output from mint.

hello, i use the SMPL mesh, but got nothing. how to do?
