### ISSUE TITLE
Visulization with 3D character

### ISSUE THREAD

**Issue by EricGuo5513** [google-research/mint#16]
Hi, thanks for your fancy work. I'm new in 3D visualization. Just curious how you visualize the generate 3D motion with character from Mixamo. Do you use blender or something? Could you possibly refer some helpful websites or something like that? 

Thanks in advance.

**Comment by WinstonDeng** [comment]
Same question. Looking forward to the animation script.

**Comment by Jevin754** [comment]
+1

**Comment by funnyQZQ** [comment]
Maybe you need some scripts like [this](https://github.com/Arthur151/ROMP#blender-addons)

**Comment by birdflies** [comment]
+1

**Comment by shanyang-me** [comment]
We used Blender + AutoRigPro(https://blendermarket.com/products/auto-rig-pro), you could download the Mixamo character (which is the easiest to rig and have corresponding joints with SMPL). Then convert our results to fbx file using the script, then import it into blender.

**Comment by wang-zm18** [comment]
Thank you for your shairing!

**Comment by wang-zm18** [comment]
@shanyang-me what is your script to convert the SMPL results to fbx files?

**Comment by shanyangmie** [comment]
@wang-zm18 I have a typo in the previous reply, not fbx but bvh. The conversion tool: https://github.com/google-research/mint/blob/main/tools/bvh_writer.py. You can convert the results to bvh then use blender to import the bvh file.

**Comment by wang-zm18** [comment]
OK，Thank you!

**Comment by h310558606** [comment]
Could you tell me how to use the bvh_writer.py? The dimension of the model output is 225, I think that  this npy file can't be the input of the bvh_writer.py.
