### ISSUE TITLE
BeatAlign

### ISSUE THREAD

**Issue by YIN95** [google-research/mint#17]
Hi Ruilong, 

I was wondering whether the kinematic beats are computed based on the whole body joints?
I cannot find these codes.

**Comment by wang-zm18** [comment]
@YIN95 Hello, Wenjie, did you find the corresponding code?

**Comment by kotomiDu** [comment]
@YIN95  @wang-zm18 @liruilong940607   I have same question, where does the kinetic velocity come from?

**Comment by liruilong940607** [comment]
Hi, please refer to the code here for beat metric calculation:

https://github.com/liruilong940607/mint/blob/main/tools/calculate_beat_scores.py

Sorry that I forgot to merge updates from my personal branch to this official repo. I just created a merge request but would need to wait for my collaborators to approve it.

**Comment by jason870509** [comment]
> Hi, please refer to the code here for beat metric calculation:
> 
> https://github.com/liruilong940607/mint/blob/main/tools/calculate_beat_scores.py
> 
> Sorry that I forgot to merge updates from my personal branch to this official repo. I just created a merge request but would need to wait for my collaborators to approve it.

Hi Ruilong, where can I download the data in '/mnt/data/aist_paper_results/*.pkl'?
