### ISSUE TITLE
How to transfer .npy file to video

### ISSUE THREAD

**Issue by loserZhang** [google-research/mint#19]
Thanks for your fancy work. I run evaluator.py file and the output file is .npy. Could you please give me some suggestions about transferring the output file to video?

**Comment by shanyang-me** [comment]
You would need to convert it to fbx suppose you want to use Blender to render out the animation.

**Comment by loserZhang** [comment]
Yes, is there any way to convert it to fbx, thanks?

**Comment by loserZhang** [comment]
Yes, is there any way to convert it to fbx? thanks.

**Comment by heheal** [comment]
> Yes, is there any way to convert it to fbx? thanks.

I also want a way to convert it to fbx. Is there a way to solve it?

**Comment by shanyang-me** [comment]
You can use our bvh converter: https://github.com/google-research/mint/blob/main/tools/bvh_writer.py to convert the npy file into a bvh file. bvh is a format for motion caption. You can import the bvh file into Blender. Then transfer the motion onto your rigged character, then render it as images.

**Comment by heheal** [comment]
> You can use our bvh converter: https://github.com/google-research/mint/blob/main/tools/bvh_writer.py to convert the npy file into a bvh file. bvh is a format for motion caption. You can import the bvh file into Blender. Then transfer the motion onto your rigged character, then render it as images.

Thank you so much.

**Comment by loserZhang** [comment]
> You would need to convert it to fbx suppose you want to use Blender to render out the animation.



> You can use our bvh converter: https://github.com/google-research/mint/blob/main/tools/bvh_writer.py to convert the npy file into a bvh file. bvh is a format for motion caption. You can import the bvh file into Blender. Then transfer the motion onto your rigged character, then render it as images.

Thank you so much

**Comment by jason870509** [comment]
> 
> Thank you so much

Hi. 
Did you success to transfer the file?
Where can I get the 'skeleton_csv_filename'?
Thanks!

**Comment by shanyang-me** [comment]
You would need to get the skeleton_csv_filename from the SMPL skeleton, I forgot to release it and now I'm no longer with Google.

**Comment by birdflies** [comment]
@jason870509  Hi, do you solve this problem?

**Comment by jason870509** [comment]
No, I still can't solve it. But if you only want to demo your .npy motion, maybe you can refer [https://github.com/yanch2116/CharacterDriven-BlenderAddon](url).

**Comment by jason870509** [comment]
> @jason870509 Hi, do you solve this problem?

No, I still can't solve it. But if you only want to demo your .npy motion, maybe you can refer
https://github.com/yanch2116/CharacterDriven-BlenderAddon

**Comment by wang-zm18** [comment]
Thank you @jason870509 ! I also met with this "npy -> vbh" problem.

**Comment by birdflies** [comment]
> > @jason870509 Hi, do you solve this problem?
> 
> No, I still can't solve it. But if you only want to demo your .npy motion, maybe you can refer https://github.com/yanch2116/CharacterDriven-BlenderAddon

Thank you.

**Comment by h310558606** [comment]
Did anyone solved the problem?

**Comment by hzy-del** [comment]
> > @jason870509 Hi, do you solve this problem?
> 
> No, I still can't solve it. But if you only want to demo your .npy motion, maybe you can refer https://github.com/yanch2116/CharacterDriven-BlenderAddon
how npy files use this ？

**Comment by hzy-del** [comment]
> > @jason870509 Hi, do you solve this problem?
> 
> No, I still can't solve it. But if you only want to demo your .npy motion, maybe you can refer https://github.com/yanch2116/CharacterDriven-BlenderAddon

how npy file use this？

**Comment by jason870509** [comment]
> 
> how npy file use this？

It appears that the author is no longer maintaining and has removed this project. Perhaps you should seek alternative ways to solve this issue.
