### ISSUE TITLE
TypeError: The `filenames` argument must contain `tf.string` elements. Got `tf.float32` elements.

### ISSUE THREAD

**Issue by wang-zm18** [google-research/mint#35]
When I completed the data preprocessing and got the tfrecord file, however, when I tried to train the model, the error occurred like this.  It seems to be the problem of tf.data.TFRecordDataset.  Thank you in advance!
![image](https://user-images.githubusercontent.com/47704679/152718682-e6c4958c-64da-46f5-91fa-4842281d0b5e.png)
![image](https://user-images.githubusercontent.com/47704679/152718706-56a33259-a671-4e57-bb5a-46552f0772b3.png)

**Comment by hzy-del** [comment]
How did you solve the problem?
