### ISSUE TITLE
  # Pad the input motion translation from 3-dim to 9-dim.

### ISSUE THREAD

**Issue by YIN95** [google-research/mint#5]
Hi, 

I was wondering why pad the translation from 3 to 9?

Best,
Wenjie

**Comment by liruilong940607** [comment]
Hi Wenjie! There was a legacy reason for that. I don't remember what experiments we were doing which requires dimension to be divided by 9, but I believe in the version we release, it does not matter any more.

**Comment by YIN95** [comment]
> Hi Wenjie! There was a legacy reason for that. I don't remember what experiments we were doing which requires dimension to be divided by 9, but I believe in the version we release, it does not matter any more.

Thanks Ruilong,

/Wenjie

**Comment by h310558606** [comment]
> 

The dimension of the model output is 225, how to change it to 219? Thanks.
