### ISSUE TITLE
bvh_writer instruction

### ISSUE THREAD

**Issue by YIN95** [google-research/mint#6]
Hi Ruilong, 

Is it possible that providing instructions on bvh_writer?
I didn't find the skeleton_csv_filename and joints_to_ignore_csv_filename. 

Best,
Wenjie

**Comment by shanyang-me** [comment]
My appologies here, I recent left google and forgot to release those csv files. You can dump those files from the SMPL skeletons.

**Comment by jason870509** [comment]
> My appologies here, I recent left google and forgot to release those csv files. You can dump those files from the SMPL skeletons.


Hi. This is my first time using SMPL.
Where can I find the “SMPL skeletons” and get the parameter need in bvh_writer? Thanks.

Best,
Jason

**Comment by shanyang-me** [comment]
Hi, checkout the SMPL website here: **https://smpl.is.tue.mpg.de/** and related papers.

**Comment by h310558606** [comment]
> 
Have you know how to use the bvh_writer file?
